@startuml

:开始;

:请求健康工具列表接口;
-> 本地是否有接口数据缓存;
if () then
  -> true;
  :获取本地缓存数据;
  ->
else
  -> false;
  :获取apk资源文件预设json;
endif

:渲染页面①;

-> 请求网络接口数据;

if () then
  -> true;
  :保存网络数据到本地;
  ->
else
-> false;
endif

:渲染页面②;

:结束;
@enduml
